[package]
authors = ["Ariel Ben-Yehuda <ariel.byd@gmail.com>"]
name = "nll-probe"
version = "0.1.0"

[dependencies]
env_logger = "0.4.3"
error-chain = "0.11.0"
log = "0.3.8"
serde = "1.0.16"
serde_derive = "1.0.16"
toml = "0.4.5"
walkdir = "2.0.1"
