python='/usr/bin/python'
rust_buildroot='/home/ariel/Rust/rust-emergency/build-debug-assertions/build'
rust_srcroot='/home/ariel/Rust/rust-emergency'
host='x86_64-unknown-linux-gnu'
cachedir='/home/ariel/Rust/nll-probe/cache'
blessed_dir='/home/ariel/Rust/nll-probe/blessed'